AWSTemplateFormatVersion: 2010-09-09
Description: Henrys Cloudformation Implementation
Metadata: 

Parameters: 

Mappings: 

Conditions: 

Resources: 
  RootRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.&api-domain;" 
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "*"
                Resource: "*"
  RootInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        -
          Ref: "RootRole"
  AppLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      Name: !Ref EnvironmentName
      Scheme: internet-facing
      SecurityGroups: 
        - String
      SubnetMappings: 
        - SubnetMapping
      Subnets: 
        - String
      Tags: 
        - Key: EnvironmentName
          Value: !Ref EnvironmentName-VPC
      Type: String

Outputs:
  VPC: 
    Description: A reference to the created VPC
    Value: !Ref VPC
    Export:
      Name: !Ref EnvironmentName-VPCID