AWSTemplateFormatVersion: 2010-09-09
Description: Henrys Network Implementation
Metadata: 

Parameters: 
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: Henrys
  VpcCIDR: 
        Description: Please enter the IP range (CIDR notation) for this VPC
        Type: String
        Default: 10.0.0.0/16

Mappings: 

Conditions: 

Resources: 
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

Outputs: